[package]
name = "gh-label"
version = "0.1.0"
description = "Simple GUI for editing GitHub labels "
homepage = "https://github.com/ferreira-tb/gh-label"
repository = "https://github.com/ferreira-tb/gh-label"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
edition = "2021"

[build-dependencies.tauri-build]
version = "1.5"
features = []

[dependencies]
serde_json = "1.0"
miho = "3"
thiserror = "1.0.56"

[dependencies.tauri]
version = "1.5"
features = ["dialog-confirm"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[features]
custom-protocol = ["tauri/custom-protocol"]
