[package]
name = "gh-gui"
version = "0.1.0"
description = "GUI for GitHub CLI"
homepage = "https://github.com/ferreira-tb/gh-gui"
repository = "https://github.com/ferreira-tb/gh-gui"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
edition = "2021"

[build-dependencies.tauri-build]
version = "1.5"
features = []

[dependencies]
serde_json = "1.0"
tauri-plugin-manatsu = "0.1"
miho = "3"
thiserror = "1.0"

[dependencies.tauri]
version = "1.5"
features = []

[dependencies.serde]
version = "1.0"
features = ["derive"]

[features]
custom-protocol = ["tauri/custom-protocol"]
