[package]
name = "gh-label"
version = "0.2.4"
publish = false

[package.description]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.authors]
workspace = true

[package.license]
workspace = true

[package.edition]
workspace = true

[build-dependencies.tauri-build]
version = "1.5.1"
features = []

[dependencies]
serde_json = "1.0.114"
thiserror = "1.0.57"
tauri-plugin-manatsu = "0.4.0"
tauri-plugin-window-state = "0.1.0"

[dependencies.tauri]
version = "1.6.0"
features = ["dialog-confirm"]

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[features]
custom-protocol = ["tauri/custom-protocol"]
