/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IDelete: typeof import('./../src/components/icons/IDelete.vue')['default']
    IEdit: typeof import('./../src/components/icons/IEdit.vue')['default']
    ILoading: typeof import('./../src/components/icons/ILoading.vue')['default']
    ISync: typeof import('./../src/components/icons/ISync.vue')['default']
    LabelChip: typeof import('./../src/components/LabelChip.vue')['default']
    LabelClone: typeof import('./../src/components/LabelClone.vue')['default']
    LabelEditor: typeof import('./../src/components/LabelEditor.vue')['default']
    LabelGrid: typeof import('./../src/components/LabelGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
